### ISSUE TITLE
name 'trainer' is not defined

### ISSUE THREAD

**Issue by imperator-maximus** [tmaham/DS-Fusion#3]
I downloaded the latent diffusion model as described 
wget -O ckpt/model.ckpt https://ommer-lab.com/files/rdm/model.ckpt
and also needed 
pip install taming-transformers-rom1504

now I am getting:

(ldm) D:\sd\DS-Fusion>python script_basic.py -s "DOG" -t "O" --one_font "False" --font_name "ani" --white_bg "True" --cartoon "True"   --ckpt_path "ckpt/model.ckpt"
Syntaxfehler.
Making style images
Der Befehl "rm" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Syntaxfehler.
usage: txt2img.py [-h] [--prompt [PROMPT]] [--outdir [OUTDIR]] [--ddim_steps DDIM_STEPS] [--plms] [--ddim_eta DDIM_ETA]
                  [--n_iter N_ITER] [--H H] [--W W] [--n_samples N_SAMPLES] [--scale SCALE] [--seed SEED] [--ema]
                  [--ckpt_path CKPT_PATH] [--embedding_path EMBEDDING_PATH] [--use_generic USE_GENERIC]
txt2img.py: error: unrecognized arguments: illustration cartoon with white background'
Ein Unterverzeichnis oder eine Datei mit dem Namen "out_cur" existiert bereits.
Global seed set to 42
Running on GPUs 0,
Loading model from ckpt/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 872.30 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: 100%|█████████████████████████████████████████████████████████████████████████| 455k/455k [00:00<00:00, 1.75MB/s]
Deleting key model_ema.decay from state_dict.
Deleting key model_ema.num_updates from state_dict.
Traceback (most recent call last):
  File "main.py", line 634, in <module>
    model = load_model_from_config(config, opt.ckpt_resume)
  File "main.py", line 32, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "D:\sd\DS-Fusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\sd\DS-Fusion\ldm\models\diffusion\ddpm.py", line 485, in __init__
    self.init_from_ckpt(ckpt_path, ignore_keys)
  File "D:\sd\DS-Fusion\ldm\models\diffusion\ddpm.py", line 209, in init_from_ckpt
    missing, unexpected = self.load_state_dict(sd, strict=False) if not only_model else self.model.load_state_dict(
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
        size mismatch for model.diffusion_model.time_embed.0.weight: copying a param with shape torch.Size([1792, 448]) from checkpoint, the shape in current model is torch.Size([1280, 320]).
        size mismatch for model.diffusion_model.time_embed.0.bias: copying a param with shape torch.Size([1792]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for model.diffusion_model.time_embed.2.weight: copying a param with shape torch.Size([1792, 1792]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for model.diffusion_model.time_embed.2.bias: copying a param with shape torch.Size([1792]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([448, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
        size mismatch for model.diffusion_model.input_blocks.0.0.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.0.in_layers.0.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.0.in_layers.0.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.0.in_layers.2.weight: copying a param with shape torch.Size([448, 448, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 320, 3, 3]).
        size mismatch for model.diffusion_model.input_blocks.1.0.in_layers.2.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.0.emb_layers.1.weight: copying a param with shape torch.Size([448, 1792]) from checkpoint, the shape in current model is torch.Size([320, 1280]).
        size mismatch for model.diffusion_model.input_blocks.1.0.emb_layers.1.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.0.out_layers.0.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.0.out_layers.0.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.0.out_layers.3.weight: copying a param with shape torch.Size([448, 448, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 320, 3, 3]).
        size mismatch for model.diffusion_model.input_blocks.1.0.out_layers.3.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.norm.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.norm.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.proj_in.weight: copying a param with shape torch.Size([448, 448, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for model.diffusion_model.input_blocks.1.1.proj_in.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_q.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_k.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_v.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.weight: copying a param with shape torch.Size([3584, 448]) from checkpoint, the shape in current model is torch.Size([2560, 320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.bias: copying a param with shape torch.Size([3584]) from checkpoint, the shape in current model is torch.Size([2560]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2.weight: copying a param with shape torch.Size([448, 1792]) from checkpoint, the shape in current model is torch.Size([320, 1280]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_q.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([448, 768]) from checkpoint, the shape in current model is torch.Size([320, 1280]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([448, 768]) from checkpoint, the shape in current model is torch.Size([320, 1280]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.proj_out.weight: copying a param with shape torch.Size([448, 448, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for model.diffusion_model.input_blocks.1.1.proj_out.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.0.in_layers.0.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.0.in_layers.0.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.0.in_layers.2.weight: copying a param with shape torch.Size([448, 448, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 320, 3, 3]).
        size mismatch for model.diffusion_model.input_blocks.2.0.in_layers.2.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.0.emb_layers.1.weight: copying a param with shape torch.Size([448, 1792]) from checkpoint, the shape in current model is torch.Size([320, 1280]).
        size mismatch for model.diffusion_model.input_blocks.2.0.emb_layers.1.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.0.out_layers.0.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.0.out_layers.0.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.0.out_layers.3.weight: copying a param with shape torch.Size([448, 448, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 320, 3, 3]).
        size mismatch for model.diffusion_model.input_blocks.2.0.out_layers.3.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.norm.weight: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.norm.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.proj_in.weight: copying a param with shape torch.Size([448, 448, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
        size mismatch for model.diffusion_model.input_blocks.2.1.proj_in.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_q.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_k.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_v.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.weight: copying a param with shape torch.Size([448, 448]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.bias: copying a param with shape torch.Size([448]) from checkpoint, the shape in current model is torch.Size([320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.weight: copying a param with shape torch.Size([3584, 448]) from checkpoint, the shape in current model is torch.Size([2560, 320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.bias: copying a param with shape torch.Size([3584]) from checkpoint, the shape in current model is torch.Size([2560]).
        size mismatch for model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2.weight: copying a param with shape torch.Size([448, 1792]) from checkpoint, the shape in current model is torch.Siz
...
[deleted hundreds of similar lines]
...
        size mismatch for first_stage_model.post_quant_conv.weight: copying a param with shape torch.Size([16, 16, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 4, 1, 1]).
        size mismatch for first_stage_model.post_quant_conv.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([4]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 863, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

Thank you!

**Comment by tmaham** [comment]
This looks like an issue with the checkpoint file incompatibility. To reduce confusion, we have added link to the checkpoint model.ckpt we used in our project in the updated readme. this should hopefully resolve this issue.
