### ISSUE TITLE
error with run script_basic.py

### ISSUE THREAD

**Issue by lzghades** [tmaham/DS-Fusion#4]
When run "python script_basic.py -s "DRAGON" -t "R" --one_font "False" --font_name "ani" --white_bg "True" --cartoon "True"   --ckpt_path "model.ckpt""

raise an error: FileNotFoundError: [Errno 2] No such file or directory: 'data_style/DRAGON/samples'

**Comment by raikiriww** [comment]
You can try to delete the data_style folder and try again

**Comment by tmaham** [comment]
you may also try adding '--make_data True' 

this will enforce a rewrite of the style folder
