### ISSUE TITLE
Which pre-trained weight do you use in your paper?

### ISSUE THREAD

**Issue by psm1000** [tmaham/DS-Fusion#8]
There are many pre-trained models in [source](https://github.com/CompVis/latent-diffusion). Which pre-trained model do you use for "model.ckpt"?

**Comment by tmaham** [comment]
we used the pretrained model with latent diffusion model + bert. we provide a link [model.ckpt](https://drive.google.com/file/d/1FuwXUk8Ht-UZ2J-vCAg9MOJRPqd8iY-F/view) so its more convenient
